/**
 * Database types - This file will be generated by Supabase CLI
 * after running: supabase gen types typescript --linked > src/types/database.types.ts
 *
 * For now, using placeholder types
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      workspaces: {
        Row: {
          id: string
          owner_id: string
          name: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          owner_id: string
          name: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          owner_id?: string
          name?: string
          created_at?: string
          updated_at?: string
        }
      }
      pages: {
        Row: {
          id: string
          workspace_id: string
          parent_id: string | null
          title: string
          icon: string | null
          cover_url: string | null
          content_json: Json
          content_text: string
          source: string | null
          source_id: string | null
          archived: boolean
          position: number
          is_folder: boolean
          template_id: string | null
          import_source: string | null
          import_metadata: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          workspace_id: string
          parent_id?: string | null
          title: string
          icon?: string | null
          cover_url?: string | null
          content_json?: Json
          content_text?: string
          source?: string | null
          source_id?: string | null
          archived?: boolean
          position?: number
          is_folder?: boolean
          template_id?: string | null
          import_source?: string | null
          import_metadata?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          workspace_id?: string
          parent_id?: string | null
          title?: string
          icon?: string | null
          cover_url?: string | null
          content_json?: Json
          content_text?: string
          source?: string | null
          source_id?: string | null
          archived?: boolean
          position?: number
          is_folder?: boolean
          template_id?: string | null
          import_source?: string | null
          import_metadata?: Json
          created_at?: string
          updated_at?: string
        }
      }
      projects: {
        Row: {
          id: string
          workspace_id: string
          title: string
          description: string | null
          status: string
          start_date: string | null
          end_date: string | null
          source: string | null
          source_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          workspace_id: string
          title: string
          description?: string | null
          status?: string
          start_date?: string | null
          end_date?: string | null
          source?: string | null
          source_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          workspace_id?: string
          title?: string
          description?: string | null
          status?: string
          start_date?: string | null
          end_date?: string | null
          source?: string | null
          source_id?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      dashboard_widgets: {
        Row: {
          id: string
          workspace_id: string
          project_id: string | null
          title: string
          widget_type: string
          chart_type: string
          data_source: string
          query_config: Json
          layout: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          workspace_id: string
          project_id?: string | null
          title: string
          widget_type?: string
          chart_type: string
          data_source: string
          query_config?: Json
          layout?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          workspace_id?: string
          project_id?: string | null
          title?: string
          widget_type?: string
          chart_type?: string
          data_source?: string
          query_config?: Json
          layout?: Json
          created_at?: string
          updated_at?: string
        }
      }
      tasks: {
        Row: {
          id: string
          workspace_id: string
          project_id: string | null
          page_id: string | null
          title: string
          status: string
          priority: number
          due_date: string | null
          source: string | null
          source_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          workspace_id: string
          project_id?: string | null
          page_id?: string | null
          title: string
          status?: string
          priority?: number
          due_date?: string | null
          source?: string | null
          source_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          workspace_id?: string
          project_id?: string | null
          page_id?: string | null
          title?: string
          status?: string
          priority?: number
          due_date?: string | null
          source?: string | null
          source_id?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      finance_entries: {
        Row: {
          id: string
          workspace_id: string
          project_id: string | null
          page_id: string | null
          type: string
          category: string
          amount: number
          date: string
          note: string | null
          source: string | null
          source_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          workspace_id: string
          project_id?: string | null
          page_id?: string | null
          type: string
          category: string
          amount: number
          date: string
          note?: string | null
          source?: string | null
          source_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          workspace_id?: string
          project_id?: string | null
          page_id?: string | null
          type?: string
          category?: string
          amount?: number
          date?: string
          note?: string | null
          source?: string | null
          source_id?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      page_links: {
        Row: {
          id: string
          source_page_id: string
          target_page_id: string
          link_type: string
          created_at: string
        }
        Insert: {
          id?: string
          source_page_id: string
          target_page_id: string
          link_type?: string
          created_at?: string
        }
        Update: {
          id?: string
          source_page_id?: string
          target_page_id?: string
          link_type?: string
          created_at?: string
        }
      }
      page_templates: {
        Row: {
          id: string
          workspace_id: string
          title: string
          description: string | null
          icon: string | null
          content_json: Json
          is_default: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          workspace_id: string
          title: string
          description?: string | null
          icon?: string | null
          content_json?: Json
          is_default?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          workspace_id?: string
          title?: string
          description?: string | null
          icon?: string | null
          content_json?: Json
          is_default?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      page_versions: {
        Row: {
          id: string
          page_id: string
          title: string
          content_json: Json
          content_text: string
          version_number: number
          created_at: string
          created_by: string | null
        }
        Insert: {
          id?: string
          page_id: string
          title: string
          content_json: Json
          content_text: string
          version_number?: number
          created_at?: string
          created_by?: string | null
        }
        Update: {
          id?: string
          page_id?: string
          title?: string
          content_json?: Json
          content_text?: string
          version_number?: number
          created_at?: string
          created_by?: string | null
        }
      }
      // Other tables will be added after schema is created
    }
    Views: {}
    Functions: {}
    Enums: {}
  }
}
